name: build-docker-image

on:
  push:
    branches:
      - master
  schedule:
    - cron: '7 0 * * sun'

jobs:
  make-date-tag:
    runs-on: ubuntu-latest
    outputs:
      dtag: ${{ steps.mkdatetag.outputs.dtag }}
    steps:
    - name: make date tag
      id: mkdatetag
      run: echo "::set-output name=dtag::$(date +%Y%m%d-%H%M)"

  build:
    runs-on: ubuntu-latest
    if: startsWith(github.repository, 'opensciencegrid/')
    strategy:
      matrix:
        dver: ['7', '8']
        repo: ['development', 'testing', 'release']
        series: ['3.5', '3.6']
    needs: make-date-tag
    steps:
    - name: checkout docker-software-base
      uses: actions/checkout@v2

    - id: generate-tag-list
      env:
        DVER: ${{ matrix.dver }}
        REPO: ${{ matrix.repo }}
        SERIES: ${{ matrix series }}
        TIMESTAMP: ${{ needs.make-date-tag.outputs.dtag }}
      run: |
        TAG_PREFIXES=("$SERIES-el$DVER-")
        TAG_NAMES="$REPO $REPO-$TIMESTAMP"
        [[ $DVER == 7 ]] && TAG_PREFIXES+=('')
        [[ $REPO == 'testing' ]] && [[ $SERIES == '3.5' ]] && TAG_NAMES="$TAG_NAMES fresh $TIMESTAMP"
        tag_list=''
        for tag_prefix in "${TAG_PREFIXES[@]}"; do
            for base in $TAG_NAMES; do
                tag="${GITHUB_REPOSITORY/opensciencegrid\/docker-/opensciencegrid/}:$tag_prefix$base"
                tag_list="${tag_list}${tag_list:+,}${tag}"
            done
        done
        echo "::set-output name=taglist::$tag_list"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v2.2.0
      with:
        push: true
        build-args: IMAGE_BASE_TAG=centos${{ matrix.dver }}
        tags: "${{ steps.generate-tag-list.outputs.taglist }}"

  dispatch:
    runs-on: ubuntu-latest
    if: startsWith(github.repository, 'opensciencegrid/')
    needs: build
    strategy:
      matrix:
        dispatch-repo:
        - docker-compute-entrypoint
        - docker-frontier-squid
        - docker-hosted-ce
        - docker-htcondor-ce
        - docker-xcache
        - gratia-probe
    steps:

    - name: dispatch build ${{ matrix.dispatch-repo }}
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: opensciencegrid/${{ matrix.dispatch-repo }}
        event-type: dispatch-build
