name: build-docker-image

on:
  push:
    branches:
      - master
  repository_dispatch:
    types: [dispatch-build]
  workflow_dispatch:

jobs:
  make-date-tag:
    runs-on: ubuntu-latest
    outputs:
      dtag: ${{ steps.mkdatetag.outputs.dtag }}
    steps:
    - name: make date tag
      id: mkdatetag
      run: echo "::set-output name=dtag::$(date +%Y%m%d-%H%M)"

  build:
    runs-on: ubuntu-latest
    if: startsWith(github.repository, 'opensciencegrid/')
    strategy:
      fail-fast: False
      matrix:
        dver: ['7', '8']
        repo: ['development', 'testing', 'release']
        series: ['3.5', '3.6']
    needs: make-date-tag
    steps:
    - name: checkout docker-software-base
      uses: actions/checkout@v2

    - id: generate-tag-list
      env:
        DVER: ${{ matrix.dver }}
        REPO: ${{ matrix.repo }}
        SERIES: ${{ matrix.series }}
        TIMESTAMP: ${{ needs.make-date-tag.outputs.dtag }}
      run: |
        docker_repo=${GITHUB_REPOSITORY/opensciencegrid\/docker-/opensciencegrid/}
        tags=()
        for registry in hub.opensciencegrid.org docker.io; do
          tags+=( $registry/$docker_repo:$SERIES-el$DVER-$REPO{,-$TIMESTAMP} )
          if [[ $SERIES-el$DVER-$REPO = 3.5-el7-testing ]]; then
            tags+=( $registry/$docker_repo:{fresh,$TIMESTAMP} )
        fi
        done
        # This causes the tag_list array to be comma-separated below,
        # which is required for build-push-action
        tag_list=$(IFS=,; echo "${tags[*]}")
        echo "::set-output name=taglist::${tag_list}"

    - id: generate-image-base
      env:
        DVER: ${{ matrix.dver }}
      run: |
        case "$DVER" in
          9) image_base="quay.io/centos/centos:stream9";;
          8) image_base="quay.io/centos/centos:stream8";;
          7) image_base="docker.io/centos:centos7";;
          *) echo "Unknown distro version: $DVER"; exit 1;;
        esac
        echo "::set-output name=imagebase::${image_base}"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        
    - name: Log in to OSG Harbor
      uses: docker/login-action@v1
      with:
        registry: hub.opensciencegrid.org
        username: ${{ secrets.OSG_HARBOR_ROBOT_USER }}
        password: ${{ secrets.OSG_HARBOR_ROBOT_PASSWORD }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v2.2.0
      with:
        context: .
        push: true
        build-args: |
          IMAGE_BASE=${{ steps.generate-image-base.outputs.imagebase }}
          BASE_YUM_REPO=${{ matrix.repo }}
          OSG_RELEASE=${{ matrix.series }}
        tags: "${{ steps.generate-tag-list.outputs.taglist }}"

  dispatch:
    runs-on: ubuntu-latest
    if: startsWith(github.repository, 'opensciencegrid/')
    needs: build
    strategy:
      matrix:
        dispatch-repo:
        - docker-compute-entrypoint
        - docker-frontier-squid
        - docker-oidc-agent
        - docker-ospool-cm
        - docker-xcache
        - docker-xrootd-standalone
        - gratia-probe
        - open-science-pool-registry
        - osg-repo-scripts
        - osgvo-docker-pilot
        - images

    steps:

    - name: dispatch build ${{ matrix.dispatch-repo }}
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.REPO_ACCESS_TOKEN }}
        repository: opensciencegrid/${{ matrix.dispatch-repo }}
        event-type: dispatch-build
