name: build-docker-image

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '7 0 * * sun'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: checkout docker-software-base
      uses: actions/checkout@v2
      with:
        path: docker-software-base
        fetch-depth: 1

    - name: build docker image
      working-directory: docker-software-base
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      run: ./travis/build_docker.sh

